Upgrade rust version in Cargo.toml and mise.toml to 1.96.0
The current rust version (1.93.0) fails to compile standard_knowledge
with the following error:

```
error: failed to compile `standard_knowledge_cli v0.1.1 (/media/data/shane/src/standard_knowledge/cli)`, intermediate artifacts can be found at `/
media/data/shane/src/standard_knowledge/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  rustc 1.93.0 is not supported by the following package:
    kstring@2.0.5 requires rustc 1.96.0
  Either upgrade rustc or select compatible dependency versions with
  `cargo update <name>@<current-ver> --precise <compatible-ver>`
  where `<compatible-ver>` is the latest version supporting rustc 1.93.0
```